# NUMPY
NumPy consists of a powerful data structure called multidimensional arrays. Pandas is another powerful Python library that provides fast and easy data analysis platform.

NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing.

The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

In [6]:
#first we have to install numpy so to do that we use this command:-
!pip install numpy

In [7]:
#once installed we need to import numpy library ny using command:-
import numpy as np

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.


numpy's array class is very usefull since it has various important and useful attributes
so to start with we have to create an array  using numpy

In [3]:
#to create and array .
arr = np.array([1,2,3])
# an array named arr is created with dimensions (3,1).

In [4]:
arr

array([1, 2, 3])

In [5]:
print(arr)

[1 2 3]


Now their are various operations which can performed on this array like:-

:-.dtype = the number of axes (dimensions) of the array.

:-.shape = the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

:-.data = the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

:-.size = he total number of elements of the array. This is equal to the product of the elements of shape.

:-.itemsize = :-.dtypethe size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

:-.ndim = the number of axes (dimensions) of the array.

In [6]:
arr.dtype

dtype('int32')

In [7]:
b = arr.dtype

dtype('int32')

In [9]:
arr.shape

(3,)

In [10]:
arr.data

In [11]:
arr.itemsize

4

In [12]:
arr.ndim

1

In [13]:
arr.size

3

In [14]:
mav = np.array([[1,2,3],[1,2,3]])

In [15]:
mav.shape

(2, 3)

In [16]:
mav.dtype

dtype('int32')

In [19]:
mav.ndim

2

In [20]:
mav.data

In [21]:
mav.itemsize

4

In [23]:
mav.size

6

In [24]:
lp = np.array([[1,2,3],[1,2,3],[1,2,3,4]])

In [25]:
lp

array([list([1, 2, 3]), list([1, 2, 3]), list([1, 2, 3, 4])], dtype=object)

Note that if elements are not same in number then it is stored as array of list

In [27]:
print(lp)

[list([1, 2, 3]) list([1, 2, 3]) list([1, 2, 3, 4])]


In [28]:
lp.data

In [29]:
lp.itemsize

8

In [30]:
lp.size

3

In [31]:
lp.ndim

1

In [32]:
lp.shape

(3,)

In [33]:
lp.dtype

dtype('O')

# METHODS FOR ARRAY CREATION

In [35]:
#BASIC ONE IS np.array
b = np.array([[1,2,3],[2,4,5],[3,5,6]])

In [36]:
b

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

In [37]:
print(b)

[[1 2 3]
 [2 4 5]
 [3 5 6]]


In [38]:
#for complex array creation
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [39]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [40]:
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [41]:
b = np.zeros((3,4))

In [42]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
 c =np.ones((3,4))

In [45]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
# integer we have to specify the data type
c = np.ones( (2,3), dtype=np.int16 )  

In [56]:
c

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [57]:
print(c)

[[1 1 1]
 [1 1 1]]


In [8]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [9]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [10]:
#to create a sequence of numbers in an array use np.arrange(starting point,ending number(not included),step size)
c = np.arange( 10, 30, 5 )

In [11]:
c

array([10, 15, 20, 25])

In [12]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [13]:
#for using pi we need to import pi from numpy so:-
from numpy import pi

In [15]:
#using of linespace :- it generates all numbers from begining to end point at equal spacing till we want numbers
np.linspace( 0, 2, 9 )   

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
x = np.linspace( 0, 2*pi, 100 ) 

In [17]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [19]:
# other functions like zeros_like(x) it generates array with zeroes with same shape as x
x = np.arange(6)
x = x.reshape((2, 3))
np.zeros_like(x)


array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
from numpy import random
np.random.rand(3,2)

array([[0.15588635, 0.08819666],
       [0.07845756, 0.48803029],
       [0.90125152, 0.48017691]])

basic operations like multiplication, addition and division, to the power  can be performed in the array

In [30]:
#for matrix elementwise product between two matrix we use * where as for matrix product we use @
A = np.array( [[1,1],
           [0,1]] )
B = np.array( [[2,0],
             [3,4]] )
A*B

array([[2, 0],
       [0, 4]])

In [31]:
A@B

array([[5, 4],
       [3, 4]])

In [32]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [36]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

in numpy axis  = 0 means coloumns and axis  = 1 means rows

In [35]:
b.sum(axis=1) 

array([ 6, 22, 38])

In [37]:
b.sum(axis=0) 

array([12, 15, 18, 21])